# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

// loldisclaimer

user_pref("browser.cache.disk.enable", false);
user_pref("network.http.use-cache", false);
user_pref("extensions.enabledAddons", "run-fullscreen%40helpful-stuff.ru:0.1.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.2");
