// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.cache.disk.enable", false);
user_pref("browser.startup.homepage", "https://dashboard.chaosdorf.space/");
user_pref("browser.startup.homepage_override.buildID", "20220315101459");
user_pref("browser.startup.homepage_override.mstone", "91.7.1");
user_pref("network.http.use-cache", false);
