  - hosts: dashpi
    remote_user: pi
    tasks:
      - name: ensure that git is installed
        apt: name=git-core state=installed
        become: yes
      - name: ensure that build-essential is installed
        apt: name=build-essential state=installed
      - name: download vusb-i2c
        git:
            repo: https://github.com/derf/vusb-i2c.git
            dest: /home/pi/vusb-i2c
      - name: ensure that libusb-dev is installed
        apt: name=libusb-dev state=installed
        become: yes
      - name: compile vusb-i2c
        make:
            chdir: /home/pi/vusb-i2c/commandline
            target: all
      - name: install vusb-i2c
        make:
            chdir: /home/pi/vusb-i2c/commandline
            target: install
        become: yes
      - name: copy 3rgbfade script
        copy:
            src: ../bin/3rgbfade
            dest: /usr/local/bin/3rgbfade
            owner: root
            group: staff
            mode: 0755
        become: yes
      - name: copy 3rgbfade systemd unit file
        copy:
            src: ../etc/systemd/system/micromoody-anim.service
            dest: /etc/systemd/system/micromoody-anim.service
            owner: root
            group: root
            mode: 0644
        become: yes
      - name: ensure 3rgbfade service is enabled and running
        systemd:
            name: micromoody-anim.service
            state: started
            enabled: yes
            daemon_reload: yes
        become: yes
