  - hosts: dashpi
    remote_user: root
    tasks:
      - name: ensure that firefox-esr is installed
        apk: name=firefox-esr state=present
      - name: copy Firefox profile folder
        copy:
            src: ../home/.mozilla/firefox
            dest: /home/dashpi/.mozilla/
      # TODO: sway-config
