  - hosts: dashpi.chaosdorf.space
    tasks:
      - name: install the UI
        community.general.snap:
          name: ubuntu-frame
          state: present
      - name: install browser and set url
        community.general.snap:
          name: wpe-webkit-mir-kiosk
          state: present
          options: 
            - url=https://dashboard.chaosdorf.space/
